# Change these first
owner: Jordan-Afonso-OCC # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: CCAPI Get customer
    url: $GET_CUSTOMER_URL
    headers:
      - "Authorization: Bearer $SECRET_TOKEN"
      - "Content-Type: application/json"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-page
  logoUrl: https://logos-download.com/wp-content/uploads/2016/05/LOccitane_en_Provence_logo_logotype.png
  name: CCAPI Status Page
  introTitle: "**Welcome** on the CCAPI status page"
  introMessage: "You can check the heath of each endpoint"
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
