owner: Jordan-Afonso-OCC # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: CCAPI Get customer
    url: $GET_CUSTOMER_URL
    headers:
      - "Authorization: Bearer $SECRET_TOKEN"
      - "Content-Type: application/json"

status-website:
  baseUrl: /status-page
  logoUrl: https://logos-download.com/wp-content/uploads/2016/05/LOccitane_en_Provence_logo_logotype.png
  name: CCAPI Status Page
  introTitle: "**Welcome** on the CCAPI status page"
  introMessage: "You can check the heath of each endpoint"
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  i18n:
    footer: ""

